### PR TITLE
Upgrade to Bootstrap 5

### PR DESCRIPTION
**Pull request by kinow**
This will take a while, but I think I can slowly add more commits and changes here until our site is upgraded to the latest version of Bootstrap.

I already liked how the text looked with the new fonts. Luckily we don't rely a lot on the Bootstrap styles, and our docs are quite simple. So it shouldn't be too hard.

~Once this is done, I will combine with another change I have stashed to add an automatic table of contents with Hugo, fixed on the sidebar (as right now I have to scroll up and down to navigate the contents :grimacing: ) - https://github.com/apache/jena-site/compare/main...kinow:sidebar-toc?expand=1~ (will create a follow up for this one).

Cheers
Bruno

### CODE REVIEW

**Comment by kinow** [comment]
@afs, others, I think this is ready for review :+1: It should create a better experience for readers, and also make it look a little closer to Fuseki UI (fonts, elements, etc.). I will prepare another PR after this one is merged to propose a change to table of contents.

Some screenshots of before/after for posterity.

Screen Shot 2023-01-12 at 23 28 34-fullpage
Screen Shot 2023-01-12 at 23 29 01-fullpage
Screen Shot 2023-01-12 at 23 29 20-fullpage

Screen Shot 2023-01-12 at 23 28 48-fullpage
Screen Shot 2023-01-12 at 23 29 08-fullpage
Screen Shot 2023-01-12 at 23 29 31-fullpage


Cheers

**Comment by kinow** [comment]
To review: simply run `hugo server watch` to render it locally. I modified the RDF API to use backticks and chose a programming language for the editor to have different code highlight. Also tested a few other pages with the breadcrumb, icons (getting started), code, tables, etc.

But it would still be good for others to take a look if the rest of the content is rendering correctly.

Icons were not a drop-in replacement. So anywhere we had icons before, will need to be manually adjusted to the new Bootstrap icons.

I also tested mobile/responsive, including the navigation menu. The only breaking changes, I think, were:

- Moved three top menu items to the right as I think we could separate all into two categories
- The Jena logo at the top menu is slightly bigger
- The getting started used Jena's logo for each entry, but I used icons as in the top level menu

Glad to adjust it based on any feedback :+1: 

-Bruno

**Comment by kinow** [comment]
Rebased.

**Review by afs — APPROVED** [review]
Could you let dev@ know the site appearance has changed when you've merged this? Thanks.

**Comment by kinow** [comment]
> Could you let dev@ know the site appearance has changed when you've merged this? Thanks.

Done!

https://markmail.org/thread/dcfebajupxs2vmao

Thanks!!!

**Pull request merged**
