### PR TITLE
Moved breadcrumbs from javascript to be Hugo generated

### PR DESCRIPTION
**Pull request by rlenferink**
This will remove the `breadcrumbs.js` javascript file which 'on the fly' serves the breadcrumbs. Instead the breadcrumbs will be generated during the website generation phase now.

/cc @afs

### CODE REVIEW

**Comment by afs** [comment]
Looks good.

I'll use this as a way to check the details of our new processes. First, confirm the build job working, then switch to gitpubsub, and publish the Hugo site, then apply this and see it flow to the published site.

**Comment by rlenferink** [comment]
Thanks Andy! 

I think the only thing left to do is setup polling SCM for the build job. After that this PR is a perfect test to verify the complete path.

**Comment by afs** [comment]
SCM polling is enabled.

**Comment by rlenferink** [comment]
Thankx Andy!

**Pull request merged**
