### PR TITLE
Make the menu more alphabetical

### PR DESCRIPTION
**Pull request by kinow**
@afs probably my OCD, but it has always bothered me when I had to search things in the docs, and the items in the menu didn't follow an order (or my brain didn't recognize one.)

What about sorting the entries in more-or-less an alphabetical order? The “Learn” menu has the "Overview“ items that I would put first as they serve as introduction to each subsection. But for the other items I think we can make an effort to keep them more or less in alphabetical order? Not a big issue if eventually we add an item in the wrong order, as it can be fixed later (we can also move them to YAML later, automating the sorting process).

WDYT?

image

image

image

### CODE REVIEW

**Comment by kinow** [comment]
p.s. I noticed it again today when I went to search the docs for GeoSparql. In the end, I couldn't locate the link. So I searched this repository and found https://jena.apache.org/documentation/geosparql/. Any reason why it's not added to the main menu yet? Thanks!

**Comment by afs** [comment]
Re: GeoSPARQL - an omission.

Could we move Fuseki up above the line as "Fuseki Triplestore" getting the most important entry points at the top.

Then alphabetic is fine for now. I think it needs some refinement in groups of importance but one thing at a time!

**Review by afs — APPROVED** [review]

**Comment by kinow** [comment]
@afs I've added GeoSPARQL, and also moved the Fuseki item just below the Overview link, and renamed to Fuseki Triplestore. Or did you mean to move it above the divider line, with the other Tutorials links?

image

**Comment by afs** [comment]
I thought above the line.

Fuseki is now many users entry point into Jena. Not so true when the website was designed!

**Comment by kinow** [comment]
> I thought above the line.
> 
> Fuseki is now many users entry point into Jena. Not so true when the website was designed!

image

Like this? :smiley:

**Comment by afs** [comment]
Yes!

**Comment by kinow** [comment]
Menu updated (have to hard-refresh the browser). Thanks @afs !

**Pull request merged**
